name: cfonline
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - arrow-cpp=19.0.0
  - async-timeout=5.0.1
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - charset-normalizer=3.3.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - datasets=3.3.2
  - dill=0.3.8
  - expat=2.7.1
  - ffmpeg=4.3
  - freetype=2.13.3
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.12.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.4.2
  - numexpr=2.10.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.6.0
  - orc=2.1.1
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.1
  - propcache=0.3.1
  - pthread-stubs=0.3
  - pyarrow=19.0.0
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.2
  - requests=2.32.3
  - s2n=1.3.27
  - setuptools=72.1.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.0
      - accelerate==1.7.0
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astor==0.8.1
      - asttokens==3.0.0
      - bitsandbytes==0.46.0
      - blake3==1.0.5
      - cachetools==6.2.0
      - cbor2==5.7.0
      - cffi==1.17.1
      - click==8.2.1
      - cloudpickle==3.1.1
      - cmake==4.1.0
      - compressed-tensors==0.10.2
      - contourpy==1.3.2
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - decorator==5.2.1
      - depyf==0.19.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - einops==0.8.1
      - email-validator==2.3.0
      - evaluate==0.4.6
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastapi==0.116.1
      - fastapi-cli==0.0.10
      - fastapi-cloud-cli==0.1.5
      - fastrlock==0.8.3
      - filelock==3.19.1
      - fonttools==4.58.4
      - gguf==0.17.1
      - gym==0.26.2
      - gym-notices==0.1.0
      - h11==0.16.0
      - hf-xet==1.1.8
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - interegular==0.3.3
      - ipdb==0.13.13
      - ipython==8.37.0
      - jedi==0.19.2
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.12
      - markdown-it-py==4.0.0
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistral-common==1.8.4
      - msgpack==1.1.1
      - msgspec==0.19.0
      - nest-asyncio==1.6.0
      - ninja==1.13.0
      - nltk==3.9.1
      - numba==0.61.2
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.575.51
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - nvitop==1.5.1
      - openai==1.105.0
      - openai-harmony==0.0.4
      - opencv-python-headless==4.12.0.88
      - outlines==0.0.34
      - outlines-core==0.2.10
      - pandarallel==1.6.5
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post6
      - persist-to-disk==0.0.7
      - pexpect==4.9.0
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.51
      - protobuf==6.32.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pybase64==1.4.2
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-extra-types==2.10.5
      - pygments==2.19.1
      - pynvml==11.5.0
      - pyparsing==3.2.3
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pyzmq==27.0.2
      - ray==2.49.1
      - referencing==0.36.2
      - regex==2024.11.6
      - rich==14.1.0
      - rich-toolkit==0.15.0
      - rignore==0.6.4
      - rouge-score==0.1.2
      - rpds-py==0.27.1
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.35.2
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - stack-data==0.6.3
      - starlette==0.47.3
      - threadpoolctl==3.6.0
      - tiktoken==0.6.0
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch==1.13.1
      - torchaudio==2.7.1+cu118
      - torchvision==0.14.1
      - traitlets==5.14.3
      - transformers==4.45.2
      - triton==2.3.1
      - typer==0.17.3
      - typing-inspection==0.4.1
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - vllm==0.4.0
      - watchfiles==1.1.0
      - wcwidth==0.2.13
      - websockets==15.0.1
      - xformers==0.0.23.post1
      - xgboost==3.0.2
      - xgrammar==0.1.21
